name: Continuous Integration
on:
  push:
    branches:
    - main
    paths:
    - version.txt

  pull_request:
    branches:
    - main

  workflow_dispatch:

jobs:
  ci:
    uses: BigGeo-GIV/bg-ci/.github/workflows/ci.yml@main
    secrets:
      GH_ACCESS: ${{ secrets.GH_ACCESS }}
      JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      JF_CONAN_URL: ${{ secrets.JF_CONAN_URL }}
    with:
      conan_create: true
      build_docs: false
