name: Update Dependencies

on:
  pull_request:
    types: [labeled]

jobs:
  update-deps:
    if: ${{ github.event.label.name == 'update dependencies' }}
    uses: BigGeo-GIV/bg-ci/.github/workflows/dep-update.yml@main
    secrets:
      GH_ACCESS: ${{ secrets.GH_ACCESS }}
      JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      JF_CONAN_URL: ${{ secrets.JF_CONAN_URL }}
