name: Update Dependencies

on:
  schedule:
    - cron: '0 17 * * 6'
  workflow_dispatch:

jobs:
  update-deps:
    uses: BigGeo-GIV/bg-ci/.github/workflows/dependencies.yml@main
    secrets:
      GH_ACCESS: ${{ secrets.GH_ACCESS }}
      JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      JF_CONAN_URL: ${{ secrets.JF_CONAN_URL }}
