name: Release

on:
  workflow_dispatch:
   inputs:
    commitSHA:
      description: 'Commit SHA to release'
      required: true
      default: ''
      type: string

jobs:
  release:
    uses: BigGeo-GIV/bg-ci/.github/workflows/release.yml@main
    secrets:
      GH_ACCESS: ${{ secrets.GH_ACCESS }}
      JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      JF_CONAN_URL: ${{ secrets.JF_CONAN_URL }}
    with:
      commitSHA: ${{ inputs.commitSHA }}
