name: Version Bump
on:
  push:
    branches:
    - main
    paths-ignore:
    - version.txt

jobs:
  version-bump:
    uses: BigGeo-GIV/bg-ci/.github/workflows/versionbump.yml@main
    secrets:
      GH_ACCESS: ${{ secrets.GH_ACCESS }}
    with: { branch: main }
